### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Dinduks** [forax/jayspec#1]
Why not having the README in the project root? It would make the projet look more alive imo.

**Comment by forax** [comment]
On 06/14/2013 11:58 PM, Samy Dindane wrote:

> Why not having the README in the project root? It would make the 
> projet look more alive imo.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/forax/jayspec/issues/1.

send a pull request :)

Rémi

**Comment by Dinduks** [comment]
Is moving _jayspec/_*\* to the root ok?

**Comment by forax** [comment]
On 06/15/2013 12:57 AM, Samy Dindane wrote:

> Is moving /jayspec//*\* to the root ok?

no !
I want to have multiple-roots for that project.

Rémi
