### ISSUE TITLE
The project doesn't build

### ISSUE THREAD

**Issue by Dinduks** [forax/jayspec#4]
As you probably have noticed, the project doesn't build. 

First of all, fest-assert-2.x 20d45eb34092a1f368e32f3020858617d161e829 is broken (people commiting broken stuff on _master_, wow! :+1:). 
Then you need JUnit.
Then you need Hamcrest.
Etc. 

The best would be using _lib/*.jar_ or Maven (or something similar). 

I can try fixing this later.

**Comment by forax** [comment]
On 06/15/2013 01:08 AM, Samy Dindane wrote:

> As you probably have noticed, the project doesn't build.
> 
> First of all fest-assert-2.x 20d45eb 
> https://github.com/forax/jayspec/commit/20d45eb34092a1f368e32f3020858617d161e829 
> is broken (people commiting broken stuff on /master/, wow! :+1:).

yes, I've patched the code to run it and did not do a pull request 
because it was quite ugly :)

> Then you need JUnit.
> Then you need Hamcrest.
> Etc.

You only need them if you want to run the test

> The best would be using /lib//.jar\* or Maven (or something similar).

As I said, the best is to fix upstream.

> I can try fixing this later.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/forax/jayspec/issues/4.

Rémi

**Comment by forax** [comment]
Ok, I've removed the dependency on fest-assert.

**Comment by Dinduks** [comment]
Nice. 

I wanted to ask you if the project's abandoned last I've seen you.

**Comment by forax** [comment]
Nothing is never abandoned if it's on github :)
